### ISSUE TITLE
a example of using monaco-editor and libro-lsp to implement the lsp notebook specification

### ISSUE THREAD

**Issue by FoSuCloud** [difizen/libro#138]
Hello, could you please provide an example of using monaco-editor and libro-lsp to implement the lsp notebook specification?

**Comment by zhanba** [comment]
I think what you need is a notebook LSP client that can talk to LSP server, you can see the Libro implementation in here  https://github.com/difizen/libro/blob/d6e238efa29ba3beb84fa041a6c46672af94ab07/packages/libro-language-client/src/libro-language-client.ts#L29

Notebook LSP client implementation is depend on notebook editor.
VSCode implement a LSP client in vscode-languageserver-protocol package, it make VSCode talk to any LSP server.
( VSCode(as notebook editor) <--> VSCode LSP client <--> LSP server)

In Libro, we made Libro LSP client, which is a modified version of VSCode LSP client(a LSP client depend on Libro API instead of VSCode API).
( Libro (as notebook editor, which use monaco-editor-core) <--> Libro LSP client <--> LSP server)

So, you need a notebook editor to implement the LSP notebook specification, and monaco-editor is just code editor, so it is not enough to do what you want. Although you can use monaco-editor to implement a notebook editor, just like what VSCode and Libro do!

**Comment by FoSuCloud** [comment]
Thank you very much for your answer!
